# DBT Project - CIVITAS BRT
name: 'civitas_brt'
version: '1.0.0'
config-version: 2

# Diretórios
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configurações globais
models:
  civitas_brt:
    +persist_docs:
      relation: true
      columns: true
    
    # Bronze layer (raw data)
    bronze:
      +materialized: table
      +schema: bronze
      
    # Silver layer (staging/cleaned)
    staging:
      +materialized: view
      +schema: staging
      
    # Gold layer (marts/aggregated)
    marts:
      +materialized: table
      +schema: marts

# Variáveis
vars:
  project_id: "{{ env_var('GCP_PROJECT_ID', 'rj-civitas') }}"
  dataset_raw: "{{ env_var('BQ_DATASET_RAW', 'brt_raw') }}"
  dataset_staging: "{{ env_var('BQ_DATASET_STAGING', 'brt_staging') }}"
  dataset_gold: "{{ env_var('BQ_DATASET_GOLD', 'brt_gold') }}"
