version: '3.8'

services:
  # Postgres database for Prefect Server
  postgres:
    image: postgres:13
    container_name: prefect-postgres
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - prefect-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prefect Server
  prefect-server:
    image: prefecthq/prefect:1.4.1-python3.10
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT__SERVER__DATABASE__CONNECTION_URL: postgresql://prefect:prefect@postgres:5432/prefect
    ports:
      - "4200:4200"
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - prefect-network
    volumes:
      - prefect-data:/root/.prefect

  # Prefect Agent (Docker)
  prefect-agent:
    image: prefecthq/prefect:1.4.1-python3.10
    container_name: prefect-agent
    command: prefect agent docker start --label civitas --api http://prefect-server:4200
    environment:
      PREFECT__CLOUD__API: http://prefect-server:4200
      PREFECT__CLOUD__AGENT__LABELS: '["civitas"]'
    depends_on:
      - prefect-server
    networks:
      - prefect-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - prefect-data:/root/.prefect
    restart: unless-stopped

networks:
  prefect-network:
    driver: bridge

volumes:
  postgres-data:
  prefect-data:
