services:
  # Prefect Agent (modo Core - sem backend)
  prefect-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: agent
    container_name: civitas-prefect-agent
    environment:
      # Prefect Core mode (execução local, sem servidor)
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/civitas-data-eng-8feab1c31a9a.json
    env_file:
      - ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../credentials:/app/credentials:ro
      - ../data:/app/data
      - prefect-data:/root/.prefect
    restart: unless-stopped
    command: tail -f /dev/null

volumes:
  prefect-data:
